version: "3.7"
services:
    playerregistrar:
        build:
            args:
                REPOSRC: /github.com/sambdavidson/community-chess/src
            context: ./src
            dockerfile: playerregistrar.Dockerfile
        image: playerregistrar:latest
        networks:
            internal:
                aliases:
                    - playerregistrar
        secrets:
            - ca_cert.pem
            - pr_cert.pem
            - pr_pk.pem
        command: >
            ./playerregistrar
            --port=443
            --ca_bundle_path=/run/secrets/ca_cert.pem
            --tls_cert_path=/run/secrets/pr_cert.pem
            --tls_private_key_path=/run/secrets/pr_pk.pem
            --debug
    gameserver_master:
        build:
            args:
                REPOSRC: /github.com/sambdavidson/community-chess/src
            context: ./src
            dockerfile: gameserver.Dockerfile
        image: gameserver:latest
        networks:
            internal:
                aliases:
                    - gameserver_master
        secrets:
            - ca_cert.pem
            - gameserver_master_cert.pem
            - gameserver_master_pk.pem
        command: >
            ./gameserver
            --slave=false
            --game_port=443
            --master_port=6443
            --player_registar_address=playerregistrar:443
            --game_id=88888888-4444-2222-1111-000000000000
            --ca_bundle_path=/run/secrets/ca_cert.pem
            --master_cert_path=/run/secrets/gameserver_master_cert.pem
            --master_private_key_path=/run/secrets/gameserver_master_pk.pem
            --debug
    gameserver_slave:
        build:
            args:
                REPOSRC: /github.com/sambdavidson/community-chess/src
            context: ./src
            dockerfile: gameserver.Dockerfile
        image: gameserver:latest
        networks:
            internal:
                aliases:
                    - gameserver_slave
        secrets:
            - ca_cert.pem
            - gameserver_slave_cert.pem
            - gameserver_slave_pk.pem
        command: >
            ./gameserver
            --slave=true
            --game_port=443
            --slave_port=6443
            --master_address=community-chess_gameserver_master_1:6443
            --player_registar_address=playerregistrar:443
            --game_id=88888888-4444-2222-1111-000000000000
            --ca_bundle_path=/run/secrets/ca_cert.pem
            --slave_cert_path=/run/secrets/gameserver_slave_cert.pem
            --slave_private_key_path=/run/secrets/gameserver_slave_pk.pem
            --debug 
    debugwebserver:
        build:
            args:
                REPOSRC: /github.com/sambdavidson/community-chess/src
            context: ./src
            dockerfile: debugwebserver.Dockerfile
        image: debugwebserver:latest
        expose:
            - "80"
        ports: 
            - "8080:80"
        networks:
            internal:
                aliases:
                    - debugwebserver
        secrets:
            - ca_cert.pem
            - debug_cert.pem
            - debug_pk.pem
        command: >
            ./debugwebserver
            --port=80
            --static_dir=./static
            --ca_bundle_path=/run/secrets/ca_cert.pem
            --tls_cert_path=/run/secrets/debug_cert.pem
            --tls_private_key_path=/run/secrets/debug_pk.pem
networks:
    internal:  
secrets:
    ca_cert.pem:
        file: ./devsecrets/certs/ca_cert.pem
    pr_cert.pem:
        file: ./devsecrets/certs/playerregistrar/pr_cert.pem
    pr_pk.pem:
        file: ./devsecrets/certs/playerregistrar/pr_pk.pem
    debug_cert.pem:
        file: ./devsecrets/certs/debugadmin/debug_cert.pem
    debug_pk.pem:
        file: ./devsecrets/certs/debugadmin/debug_pk.pem
    gameserver_master_cert.pem:
        file: ./devsecrets/certs/gameserver/master/master_cert.pem
    gameserver_master_pk.pem:
        file: ./devsecrets/certs/gameserver/master/master_pk.pem
    gameserver_slave_cert.pem:
        file: ./devsecrets/certs/gameserver/slave/slave_cert.pem
    gameserver_slave_pk.pem:
        file: ./devsecrets/certs/gameserver/slave/slave_pk.pem